import { MagnifyingGlass, CheckCircle, Clock, LockKey } from "@/components/nyascans/heroicons";
import { useCallback, useEffect, useState, type ReactNode } from "react";

type Policy = { seriesId: string; seriesTitle: string; chapterCount: number; paidChapterCount: number; priceOnyx: number; autoFreeAfterDays: number | null; revision: number };
export function SeriesPaidPolicyPanel() {
  const [query, setQuery] = useState(""); const [policies, setPolicies] = useState<Policy[]>([]); const [selected, setSelected] = useState<Policy | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const load = useCallback(async () => { const response = await fetch(`/api/v1/admin/series-paid-policies?q=${encodeURIComponent(query)}`, { cache: "no-store" }); const payload = await response.json() as { data?: { policies?: Policy[] } }; if (response.ok) setPolicies(payload.data?.policies ?? []); }, [query]);
  useEffect(() => { void load(); }, [load]);
  async function save() { if (!selected) return; setBusy(true); setMessage(""); try { const response = await fetch("/api/v1/admin/series-paid-policies", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ seriesId: selected.seriesId, paidChapterCount: selected.paidChapterCount, priceOnyx: selected.priceOnyx, autoFreeAfterDays: selected.autoFreeAfterDays, expectedRevision: selected.revision || undefined }) }); const payload = await response.json() as { data?: { policies?: Policy[] }; error?: { message?: string } }; if (!response.ok) throw new Error(payload.error?.message ?? "The series paid policy could not be saved."); setPolicies(payload.data?.policies ?? []); setSelected((payload.data?.policies ?? []).find((item) => item.seriesId === selected.seriesId) ?? null); setMessage("Series paid policy saved and eligible chapters synchronized."); } catch (error) { setMessage(error instanceof Error ? error.message : "The series paid policy could not be saved."); } finally { setBusy(false); } }
  return <AdminSection title="Series Last Paid policies" icon={<LockKey size={18} />}><p className="admin-muted-copy">When Last Paid is active, each series can lock its latest N public chapters at one Paw price. A blank count uses the one-chapter, 50-Paw fallback. Auto-Free begins only when a chapter is public.</p><div className="series-paid-policy-toolbar"><MagnifyingGlass size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search series" /></div><div className="series-paid-policy-list">{policies.map((policy) => <button type="button" key={policy.seriesId} className={selected?.seriesId === policy.seriesId ? "is-selected" : ""} onClick={() => setSelected(policy)}><span>{policy.seriesTitle}</span><small>{policy.chapterCount} chapters · {policy.paidChapterCount || 1} paid · {policy.priceOnyx} Paws</small></button>)}</div>{selected ? <div className="series-paid-policy-editor"><strong>{selected.seriesTitle}</strong><label>Paid chapters (0 = fallback 1)<input type="number" min={0} max={1000} value={selected.paidChapterCount} onChange={(event) => setSelected({ ...selected, paidChapterCount: Math.max(0, Number(event.target.value)) })} /></label><label>Price per paid chapter (Paws)<input type="number" min={1} value={selected.priceOnyx} onChange={(event) => setSelected({ ...selected, priceOnyx: Math.max(1, Number(event.target.value)) })} /></label><label>Auto-Free after days<input type="number" min={1} max={3650} placeholder="Global default: 7" value={selected.autoFreeAfterDays ?? ""} onChange={(event) => setSelected({ ...selected, autoFreeAfterDays: event.target.value ? Math.max(1, Number(event.target.value)) : null })} /></label><button className="button button-primary" type="button" disabled={busy} onClick={() => void save()}><CheckCircle size={17} />{busy ? "Saving…" : "Save series policy"}</button>{message ? <p role="status"><Clock size={16} /> {message}</p> : null}</div> : <p className="admin-muted-copy">Select a series to configure its Last Paid and Auto-Free values.</p>}</AdminSection>;
}
function AdminSection({ title, icon, children }: { title: string; icon: ReactNode; children: ReactNode }) { return <section className="admin-section-card series-paid-policy-card"><header><div>{icon}<div><span>Series configuration</span><h3>{title}</h3></div></div></header>{children}</section>; }
