import { MagnifyingGlass, CheckCircle, Clock, LockKey } from "@/components/nyascans/heroicons";
import { useCallback, useEffect, useMemo, useState } from "react";

type Policy = { seriesId: string; seriesTitle: string; coverUrl?: string | null; configured?: boolean; chapterCount: number; paidChapterCount: number; priceOnyx: number; autoFreeAfterDays: number | null; revision: number };
type Props = { mode: "NORMAL" | "LAST_PAID"; defaultAutoFreeAfterDays: number; defaultPriceOnyx: number };

export function SeriesPaidPolicyPanel({ mode, defaultAutoFreeAfterDays, defaultPriceOnyx }: Props) {
  const [query, setQuery] = useState("");
  const [policies, setPolicies] = useState<Policy[]>([]);
  const [selected, setSelected] = useState<Policy | null>(null);
  const [choice, setChoice] = useState<"DEFAULT" | "CUSTOM">("DEFAULT");
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const load = useCallback(async () => { const response = await fetch(`/api/v1/admin/series-paid-policies?q=${encodeURIComponent(query)}`, { cache: "no-store" }); const payload = await response.json() as { data?: { policies?: Policy[] } }; if (response.ok) setPolicies(payload.data?.policies ?? []); }, [query]);
  useEffect(() => { void load(); }, [load]);
  const defaults = useMemo(() => policies.filter((item) => !item.configured), [policies]);
  const configured = useMemo(() => policies.filter((item) => item.configured), [policies]);
  function selectPolicy(policy: Policy) { setSelected({ ...policy }); setChoice(policy.configured ? "CUSTOM" : "DEFAULT"); setMessage(""); }
  async function save() { if (!selected) return; setBusy(true); setMessage(""); const body = { seriesId: selected.seriesId, paidChapterCount: choice === "DEFAULT" ? 0 : selected.paidChapterCount, priceOnyx: choice === "DEFAULT" ? defaultPriceOnyx : selected.priceOnyx, autoFreeAfterDays: choice === "DEFAULT" ? null : selected.autoFreeAfterDays, expectedRevision: selected.revision || undefined }; try { const response = await fetch("/api/v1/admin/series-paid-policies", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json() as { data?: { policies?: Policy[] }; error?: { message?: string } }; if (!response.ok) throw new Error(payload.error?.message ?? "The series paid policy could not be saved."); setPolicies(payload.data?.policies ?? []); setSelected((payload.data?.policies ?? []).find((item) => item.seriesId === selected.seriesId) ?? null); setMessage("Series policy saved and eligible chapters synchronized."); } catch (error) { setMessage(error instanceof Error ? error.message : "The series paid policy could not be saved."); } finally { setBusy(false); } }
  if (mode !== "LAST_PAID") return null;
  return <section className="admin-section-card series-paid-policy-card" aria-labelledby="series-paid-policy-heading"><header><div><LockKey size={18} /><div><span>Series configuration</span><h3 id="series-paid-policy-heading">Last Paid series settings</h3></div></div></header><p className="admin-muted-copy">Search a series, choose Default settings or Custom settings, then expand and save its policy. Default settings lock one public chapter at 50 Paws for {defaultAutoFreeAfterDays} days.</p><div className="series-paid-policy-toolbar"><MagnifyingGlass size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search series" aria-label="Search series" /></div><div className="series-policy-windows"><PolicyWindow title="Default series" description="Series without custom settings use the global defaults." policies={defaults} selected={selected} onSelect={selectPolicy} defaultWindow /><PolicyWindow title="Configured series" description="Series with custom Last Paid settings." policies={configured} selected={selected} onSelect={selectPolicy} /></div>{selected ? <div className="series-paid-policy-editor"><strong>{selected.seriesTitle}</strong><div className="series-policy-radio-group" role="radiogroup" aria-label="Series policy type"><label className={choice === "DEFAULT" ? "is-selected" : ""}><input type="radio" name="series-policy-choice" checked={choice === "DEFAULT"} onChange={() => setChoice("DEFAULT")} />Default settings<span>1 chapter · {defaultPriceOnyx} Paws · {defaultAutoFreeAfterDays} days</span></label><label className={choice === "CUSTOM" ? "is-selected" : ""}><input type="radio" name="series-policy-choice" checked={choice === "CUSTOM"} onChange={() => setChoice("CUSTOM")} />Custom settings<span>Choose the locked chapter count and Auto-Free period</span></label></div>{choice === "CUSTOM" ? <div className="series-paid-policy-custom-grid"><label>Paid chapters<input type="number" min={1} max={1000} value={Math.max(1, selected.paidChapterCount)} onChange={(event) => setSelected({ ...selected, paidChapterCount: Math.max(1, Number(event.target.value)) })} /></label><label>Auto-Free after days<input type="number" min={1} max={3650} value={selected.autoFreeAfterDays ?? defaultAutoFreeAfterDays} onChange={(event) => setSelected({ ...selected, autoFreeAfterDays: Math.max(1, Number(event.target.value)) })} /></label><label>Price per chapter (Paws)<input type="number" min={1} value={selected.priceOnyx} onChange={(event) => setSelected({ ...selected, priceOnyx: Math.max(1, Number(event.target.value)) })} /></label></div> : null}<button className="button button-primary" type="button" disabled={busy} onClick={() => void save()}><CheckCircle size={17} />{busy ? "Saving…" : "Save series policy"}</button>{message ? <p role="status"><Clock size={16} />{message}</p> : null}</div> : null}</section>;
}
function PolicyWindow({ title, description, policies, selected, onSelect, defaultWindow = false }: { title: string; description: string; policies: Policy[]; selected: Policy | null; onSelect: (policy: Policy) => void; defaultWindow?: boolean }) { return <section className="series-policy-window"><div className="series-policy-window-heading"><div><span>{defaultWindow ? "GLOBAL DEFAULT" : "CUSTOM OVERRIDES"}</span><h4>{title}</h4><p>{description}</p></div><small>{policies.length} series</small></div><div className="series-policy-window-list">{policies.map((policy) => <button type="button" key={policy.seriesId} className={selected?.seriesId === policy.seriesId ? "is-selected" : ""} onClick={() => onSelect(policy)}><span className="series-policy-cover">{policy.coverUrl ? <img src={policy.coverUrl} alt="" /> : <LockKey size={15} />}</span><span className="series-policy-title">{policy.seriesTitle}<small><span>{defaultWindow ? 1 : Math.max(1, policy.paidChapterCount)} chapters</span><span>{defaultWindow ? "default" : `${policy.autoFreeAfterDays ?? "global"} days`}</span></small></span></button>)}{policies.length === 0 ? <p className="admin-muted-copy">No series match this window.</p> : null}</div></section>; }
